### ISSUE TITLE
[Feature] 구매 / 판매 엔티티 및 Bid(입찰) 구현

### ISSUE THREAD

**Issue by vymr1000** [f-lab-edu/unique-auction#15]
**목표**
구매 / 판매 API 구현

**방법**
- [x] 구매 Purchase 엔티티 설계 & 구현
- [x] 판매 Sale 엔티티 설계 & 구현
- [x] 구매 판매 Purchase Bid, Sale Bid 구현

**Comment by superkkj** [comment]
1 / 2 /3 / 4 이렇게 이슈를 나눠야될거같습니다.
쉽지가 않네요 저도 한번에 Crud해서 ㅠㅠ
