### ISSUE TITLE
[Feature] 분리되어있는 Exception 통일하기

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/unique-auction#17]
**목표**
분리되어있는 Exception 통일하기
https://github.com/f-lab-edu/unique-auction/pull/14#discussion_r979413073

**방법**
asis : LoginException, UserException, ProductException... 처럼 예외가 분리되어있음
tobe :
이점이 없기에 하나의 컨트롤어드바이스 커스텀익셉션으로 통합

**Comment by superkkj** [comment]
알겠습니다!
