### ISSUE TITLE
[Feature] ProductRequest 객체가 service, repository layer까지 전달되는 코드 수정하기

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/unique-auction#24]
**목표**
request 객체가 service, repository layer까지 오면 안됩니다.

https://github.com/f-lab-edu/unique-auction/blob/develop/src/main/java/com/uniqueAuction/domain/product/service/ProductService.java#L20-L21

**방법**
controller 에서 entity로 변환해서 service에 전달하기.

**Comment by superkkj** [comment]
pass
