### ISSUE TITLE
[Feature] 프로덕트 도메인 size entity , 카테고리 , 이미지 객체 설계 및 필드 추가

### ISSUE THREAD

**Issue by superkkj** [f-lab-edu/unique-auction#31]
**목표**

현재 프로덕트에 있는 필드중 추가로 필요한 필드는 추가를 하고
사이즈 카테고리 등 필드를, 각 엔티티로 설계를 한다.

**방법**

size , image , category entity 생성 

**주의사항**

클래스 설계 단계에서 후 디비 단계로 넘어갈때 놓치지 못한 이슈가 생길수 있다.
클래스 설계를 충분히 검토해서 작성한다.

**Comment by f-lab-lion** [comment]
`entity`가 어떤것을 의미하는지에 대해서 공부하고 넘어갔으면 합니다.
그 다음 `image`나 , `category`를 하나의`entity`단위로 둘것인지를 고민해야 합니다.
