### ISSUE TITLE
[BUG] github action에 job 이름변경

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/unique-auction#43]
to @superkkj 

**Describe the bug**
github action에서 job이름이 설정되어 어떤 기능이 성공/실패 했는지 명확하게 알 수 있어야한다.

**todo**
job1, job2 처럼 되어있는 네이밍 변경

**Screenshots**
<img width="908" alt="스크린샷 2022-10-23 오전 1 49 31" src="https://user-images.githubusercontent.com/105277168/197352546-acf65912-5a68-488c-a46f-2469806b9ef5.png">

**Comment by f-lab-lion** [comment]
@superkkj 
코드 리뷰 후 develop에 머지 되면 close 해주세요.
pr을 연동해놓았다면 자동으로 그렇게 됩니다.

이슈는 reopen 하겠습니다.

**Comment by superkkj** [comment]
넵 주의하겟습니다
