### ISSUE TITLE
[BUG] user password에 plain text가 들어가는 현상

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/unique-auction#74]
## Describe the bug
JoinRequest -> user로 변형시 plain text가 encodedPassword로 들어갑니다.
이어서 바로 암호화를 한다고하더라도 순간적으로 plain text로 들어가는것은 사실입니다.
개발자의 부주의로 이 데이터를 그대로 사용할수도 있어서 원천 차단할 필요가 있습니다.

https://github.com/f-lab-edu/unique-auction/blob/c40f6839caa648b8aa4e83a811d616e2c6b50df3/src/main/java/com/uniqueauction/web/user/request/JoinRequest.java#L39-L45

**Comment by f-lab-lion** [comment]
@superkkj  
branch 연결이 안되어있네요
어느브랜치에서 반영하셨나요?

**Comment by vymr1000** [comment]
#87 PR에서 암호화된 패스워드만 들어가도록 수정하였습니다
